### ISSUE TITLE
Parsing message text into Structured data

### ISSUE THREAD

**Issue by itsbalamurali** [itsabot/abot#149]
Hi, 

I found this Cool Library (i guess can be ported in golang) https://duckling.wit.ai/ which can parse text as below 
```
“the first Tuesday of October” => {:value "2014-10-07T00:00:00.000-07:00"
                                   :grain :day}
```

Which can help plugin developers alot.

And also have custom entity recognition and training like following
https://wit.ai/docs/http/20160526#post--entities-link

**Comment by itsbalamurali** [comment]
I guess entity recognition can be added into plugin.json file

**Comment by egtann** [comment]
Their patents requirement (https://github.com/wit-ai/duckling/blob/master/PATENTS) is incompatible with Abot, and it also seemed needlessly complex and introduced another language dependency. That's why I independently built time parsing functionality into Abot in Go. See /shared/helpers/timeparse.go
There's still some minor bugs, but it works well for most cases at this point. See the test file for examples.

E




On Sat, Jun 18, 2016 at 1:52 AM -0700, "Balamurali Pandranki" <notifications@github.com> wrote:












I guess entity recognition can be added into plugin.json file
