### ISSUE TITLE
failed to process text missing user

### ISSUE THREAD

**Issue by lordadamson** [itsabot/abot#18]
It's all setup. I started the server and registered a user.
but then when I try to communicate with abot
```
abot console +13105555555
> Hi
Something went wrong with my wiring... I'll get that fixed up soon.
> hi baby 
Something went wrong with my wiring... I'll get that fixed up soon.
> 
```
and on the server it says:
```
abot server
2016/03/31 23:45:39 started Abot
2016/03/31 23:45:43 failed to process text missing user
2016/03/31 23:46:39 failed to queue scheduled event missing destination name id
2016/03/31 23:47:02 failed to process text missing user
```

So a `failed to process text missing user` for every message I send to abot.

**Comment by lordadamson** [comment]
I tried a new user with a different number and now it did work.
I believe the reason might be because I registered two users using different numbers but same email? It didn't provide any feedback telling me that it's wrong when I was registering though.

**Comment by egtann** [comment]
Good find. The latest user kind of "steals" the phone number of any previous user. That's obviously not how it should work! We should fix this.

Since numbers do change owners, it'd be great to make a plugin that listens to a UserSignup event and triggers some verification process to ensure you currently own the number (asking you to reply to the message, or enter a 4-6 digit code online).

Doing that would require extending the possible events from the three there now (https://godoc.org/github.com/itsabot/abot/shared/datatypes#PluginEvents) to include `UserSignup`. Then modify the core/handlers.go to trigger that event for any and all plugins listening.

I'll put this on the back-burner for now, but if anyone else wants to give it a go, I'm happy to accept a Pull Request or help out through the mailing list.

**Comment by waynegerard** [comment]
It definitely does - there's a unique constraint on the EMAIL column in the users table.

But, it doesn't notify you that registration failed (so it just takes you to the sign-in screen). Probably didn't make two different users with the same email though.
