### ISSUE TITLE
Sign up not working

### ISSUE THREAD

**Issue by brokenseal** [itsabot/abot#20]
Hi! Great project but I can't currently create any user, I always get this error message back

```
    {"Msg":"pq: syntax error at or near 'ON'"}
```

Any idea?
Also, why the US number limitation?

Cheers,
Davide

**Comment by egtann** [comment]
Hi David. You'll need to upgrade to Postgres 9.5+ as per the readme.

The US number limitation is due to my lack of experience with international numbers and services. If you'd like to add support, I'd be happy to accept a PR.

I'm going to close this issue. If you have any additional questions, we're happy to answer them over the mailing list.

Best,

Evan

**Comment by brokenseal** [comment]
Hi, thanks for your help and I'm sorry for the mistake.
Cheers.
