### ISSUE TITLE
Remove vendor/cookie.js

### ISSUE THREAD

**Issue by egtann** [itsabot/abot#31]
Cookie.js (`assets/vendor/js/cookie.js`) is using an incompatible GPLv3 license. Rewrite it from scratch under MIT ensuring that no code breaks in the front-end. The API may change (it may have to), but any JavaScript that calls it should reflect that change.

This is a good first issue for new contributors.

**Comment by waynegerard** [comment]
Might I suggest just using an alternative instead? https://github.com/ScottHamper/Cookies 

Not that I think anyone in their right mind at Mozilla(?) would care, but might be safer to just swap libraries and avoid a whole nasty discussion about whether something is considered "derivative work."

**Comment by egtann** [comment]
Yeah, that's the right approach.

**Comment by njaremko** [comment]
We probably don't have to change the license (Which should be LGPL if anything)...

Our source is freely available and if anyone takes our code tries to sell it, as long as they host the software on their own servers and sell the software itself then they're fine under the GPL. (That's why AGPL was created :stuck_out_tongue:)

**Comment by egtann** [comment]
I'd like to keep the licensing clean and clear: MIT. If that means a small refactor, no big deal.
