### ISSUE TITLE
Handle binaries like images

### ISSUE THREAD

**Issue by h-teske** [itsabot/abot#46]
Do you see a chance to also process binary files like images? They might get send to the bot e.g. via Slack and I'd love to handle them as well.

**Comment by egtann** [comment]
Yes, absolutely. That can be done from within the driver's handler, e.g. at the endpoint `/slack`.

Take a look at the itsabot/twilio driver for an example. func handlerTwilio could easily extract binary data from an MMS, process it as it sees fit (e.g. through a Google Vision API), and return a response based on that binary data. You could do the same thing with Slack based on the format of the request that Slack uses to notify your endpoint.

I'm going to close this issue for now, since we do have a means of handling incoming binary data, but let me know if you need any additional direction. I'd also love to feature your Slack or vision drivers on itsabot.org if that's OK with you!
