### ISSUE TITLE
Use RethinkDB instead of PostgreSQL

### ISSUE THREAD

**Issue by paulscliu** [itsabot/abot#6]
If I would like to use RethinkDB instead of PostgreSQL would it be a easy switch? Can you point the direction on where I should look? The main reason for considering RethinkDB is due to its changefeed feature. https://rethinkdb.com/docs/changefeeds/ruby/

**Comment by egtann** [comment]
Hey Paul. Rather than switch DBs, which is a massive task, have you considered registering to listen for events in your plugins? It's a new feature that I have yet to add to the guides, but you can see the API documentation here: https://godoc.org/github.com/itsabot/abot/shared/datatypes#PluginEvents

To use them, add something like follows to your plugin after you create it:

```go
p, err = plugin.New("github.com/itsabot/plugin_weather", trigger, fns)
if err != nil {
    log.Fatal(err)
}
p.Events.PostReceive = func(cmd *string) {
    p.Log.Info("received", *cmd)
}
```

Using these listeners, you'll be notified of key events as they occur in Abot's core, like when a message is received, processed, and sent.

Does that achieve the functionality you're looking to add?

**Comment by paulscliu** [comment]
Cool. Thanks for the suggestion. I will go take a look at plugin

**Comment by egtann** [comment]
Glad to hear it, Paul.  The weather plugin is a good first start and the guides should help.  I'm going to close this issue, and if you need any additional feedback or help, we're happy to answer through the mailing list.

**Comment by egtann** [comment]
FYI I've added a Plugin Events section to the Building a Plugin guide. https://github.com/itsabot/abot/wiki/Building-a-Plugin#plugin-events
