### ISSUE TITLE
Protocol Buffers

### ISSUE THREAD

**Issue by njaremko** [itsabot/abot#63]
I propose we switch our data serialization format from JSON to Protocol Buffers.

They:
-     are simpler
-     are 3 to 10 times smaller
-     are 20 to 100 times faster
-     are less ambiguous
-     generate data access classes that are easier to use programmatically

They require you to write a schema for your storage stuct, but that's trivial.

[Link to more info](https://developers.google.com/protocol-buffers/docs/overview)

**Comment by egtann** [comment]
To clarify, this would just be for the Memory storage in Postgres, correct?

**Comment by njaremko** [comment]
Yes, yes it would

**Comment by egtann** [comment]
I'm OK with that change! As we've seen already JSON has some odd quirks!

**Comment by egtann** [comment]
@njaremko I've spent some time looking into Protocol Buffers with Go. I don't know that this is the right approach. It seems to me asking people to install another dependency (which involves installing a compiler via C++) and learn the schemas is more than a small ask and quite a bit more difficult than the current JSON system. Am I correct that people writing plugins would need to learn this in order to use the Memory API?

**Comment by njaremko** [comment]
Yeah, which is why I haven't done a lot with the Idea

**Comment by njaremko** [comment]
Hahaha

**Comment by egtann** [comment]
Ok! Closing
