### ISSUE TITLE
Plugins can interrupt each other

### ISSUE THREAD

**Issue by eviltoylet** [itsabot/abot#66]
If you're in a plugin, and just happen to give a follow-up message that matches the trigger for another plugin, you'll be switched over to that plugin.

This is extremely unintuitive and not desired. The expectation is I continue to interact with the current plugin until it finishes or I abort.

**Comment by egtann** [comment]
As another point of view, this allows for more natural conversations.

Sometimes you just stop mid-conversation, then a day later you can just start talking about something else, like the weather. You don't have to tell your friend "end conversation. What's the weather like?" for him to understand. :)

What use case are you experiencing where an internal trigger of a plugin matches another plugin?

**Comment by eviltoylet** [comment]
Say you have a favorite phrase plugin:

bot: "What's your favorite phrase?"
me: "Set my alarm to 5 pm."

What happens? If this is the design you're going for, then you should document that this is going to happen. But, I think this would be a huge mistake to go this route. 

Even in natural conversations, if you switch topics abruptly you're going to cause frustration. I understand that this might be the par for drawn out text conversations... but then the more appropriate model is probably a timeout with a message from Abot indicating this is happening.

**Comment by egtann** [comment]
In a contrived example, sure. But in practice, among realistic plugins, I'm not yet convinced that it's worth giving up this feature.

In my opinion this feature allows Abot to use and understand language more naturally than most bots today, such as, Amazon's Alexa which uses the approach you're describing. To me, Abot's behavior is much more in line with my expectations as a user because it more closely mimics speaking to a human assistant, helper, or friend.

If this becomes a problem among a larger number of developers or in building plugins that would be a shame to miss, we can revisit it. I will be adding documentation explaining the feature, though, in the meantime.

**Comment by njaremko** [comment]
Perhaps we could have a boolean that determines whether a plugin is interpretable? If not, then I'll have to side with Evan, but only marginally because of that specific example. If abot is asking for an arbitrary string, and you provide one, it probably shouldn't jump to another plugin.

Overall, I think that having the ability to stop a current conversation and say "Set my alarm for 5pm", and have it work is a better choice.

**Comment by martyhimself** [comment]
Having only just started with Abot (and I must say I am very impressed!) I was wondering about this as well. 

I have no strong opinion one way or the other- but would it be easy to switch back to the previous conversation and would the state of the conversation be held in memory or persisted some way? (or is this something that is on the cards for implementation?). 

My gut feeling would be that it could be harmful to interrupt a conversation such as purchasing process, unless maybe you have Abot take initiative (push notifications?) to complete the state machine (e.g. 'Hey, would you still like to purchase those movie tickets?'). Now that would be cool :).

**Comment by egtann** [comment]
It's definitely possible to switch back and forth between plugins and not lose your place. It's all determined by when you decide to call sm.Reset and the data you choose to wipe in defining the Reset function.

If you want to maintain a session across conversations with multiple plugins, you'd just Reset state when `sm.State() >= len(sm.Handlers)` rather than on Run()

**Comment by eviltoylet** [comment]
Switching back to a plugin requires you to type the trigger words for that plugin. Then you're slapped into a state where you probably don't remember the context.

Abot really needs to be more opinionated on this. As of now, it's passing a lot of this burden onto the plugin developer.

**Comment by egtann** [comment]
Perhaps if Reset were called automatically by Abot's core on a plugin's first Run(), then automatically again when you've completed all states? You'd lose some flexibility but it would be easier.

**Comment by egtann** [comment]
If we do automatically call Reset, perhaps we should change the plugin API to have a single function call? That is we'd replace Run/FollowUp with just `Run()`. Right now that split is necessary to allow you to manually call Reset, but if we handle that automatically, then we can simplify the API.
