### ISSUE TITLE
[err] syncing dependencies, failed cmd: glock sync 'github.com/itsabot/abot'

### ISSUE THREAD

**Issue by jpjp** [itsabot/abot#7]
```
$ rpm -q golang-bin
golang-bin-1.5.3-1.fc23.x86_64
$ cd go
$ export GOPATH=$PWD
$ go get github.com/itsabot/abot
$ cd $GOPATH/src/github.com/itsabot/abot
$ cmd/setup.sh
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
   [err] syncing dependencies

failed cmd:
         glock sync 'github.com/itsabot/abot'

bash: glock: command not found
```

**Comment by jpjp** [comment]
go 1.5. ah. oops.

**Comment by jpjp** [comment]
The next problem was that $GOPATH was not in my $PATH

**Comment by egtann** [comment]
Glad the problem is sorted out!

**Comment by damtsnkff** [comment]
Since I had the same issue, I found the this link helpful : [cannot-set-gopath-on-mac-osx](http://stackoverflow.com/questions/21499337/cannot-set-gopath-on-mac-osx)

Basically, on your `~/.bash_profile`, add this :  `export GOPATH=/Users/#USERNAME#/#FOLDERNAME#/` and then after add `export PATH=$GOPATH/bin:$PATH` .

**Comment by maddymaster** [comment]
this works.. thank you

**Comment by damtsnkff** [comment]
@maddymaster I deleted my comment since I thought this was the reason of another issue I'm facing (same as #40 )

**Comment by damtsnkff** [comment]
I was right, I added a `/` at the end.
So basically to add the `$GOPATH` in the `$PATH` my `.bash_profile` looks like :
`export GOPATH=/Users/damientsenkoff/abotest` (I previously added a `/` after `abotest`)
`export PATH=$GOPATH/bin:$PATH`
