### ISSUE TITLE
Issue with adding custom plugin

### ISSUE THREAD

**Issue by samuel-pt** [itsabot/abot#75]
I've just tried to add a simple [Hello World plugin](https://github.com/samuel-pt/sample_sf), I got the below error

```
Fetching 1 plugins...
# cd .; git clone https://github.com/itsabot/shared /home/sam/work/go_workspace/src/github.com/itsabot/shared
Cloning into '/home/sam/work/go_workspace/src/github.com/itsabot/shared'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
package github.com/itsabot/shared/plugin: exit status 128

exit status 1

```

Is it trying to fetch https://github.com/itsabot/shared? I don't see such a repository.

Here is the content of my plugins.json
```
{
        "Name": "Abot",
        "Description": "Digital assistant framework",
        "Version": "0.2.0-alpha",
        "ImportPath": "github.com/itsabot/abot",
        "Dependencies": {
                "github.com/samuel-pt/sample_sf": "*"
        }
}

```

Is it possible to add plugin from other repository?

**Comment by egtann** [comment]
Yes, it should be possible. I'll look into this.

**Comment by egtann** [comment]
We run `go get ./...` beneath the covers when you do `abot p install`. It's unable to `go get` your repo because you try to import "github.com/itsabot/shared/plugin" from your own repo, but that doesn't exist. It should be "github.com/itsabot/**abot**/shared/plugin"

I'll work on making this cryptic error message clearer, though, so we can make it easier to debug this kind of issue.
